---
- name: Install required dependencies for docker...
  become: yes
  apt: name={{ item }} state=latest
  with_items:
    - apt-transport-https
    - ca-certificates
    - cron
    - gnupg2
    - software-properties-common
    - python-setuptools
    - python3-pip
  when: ansible_os_family == 'Debian'

- name: Add the required signing key to the apt keyring...
  become: yes
  apt_key: id="9DC858229FC7DD38854AE2D88D81803C0EBFCD88" url="https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
  when: ansible_os_family == 'Debian'

- name: Configure the correct repository for getting the latest docker version...
  become: yes
  apt_repository: repo="deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable" update_cache=true
  when: ansible_os_family == 'Debian'

- name: Install docker...
  become: yes
  apt: name="docker-ce" state=latest
  when: ansible_os_family == 'Debian'

- name: Ensure the docker daemon gets started on system startup...
  become: yes
  systemd: name=docker enabled=yes state=started
  when: ansible_os_family == 'Debian'